const pharmacy=require('../services/pharmacyService');const AppError=require('../utils/AppError');const{pool}=require('../config/database');
async function dashboard(req,res,next){try{res.render('pharmacy/dashboard',{title:'Pharmacy ERP',...await pharmacy.dashboard(req.user.id)});}catch(e){next(e);}}
async function inventory(req,res,next){try{res.render('pharmacy/inventory',{title:'Inventory',medicines:await pharmacy.listMedicines(req.user.id,req.query.q||''),q:req.query.q||''});}catch(e){next(e);}}
async function batches(req,res,next){try{res.render('pharmacy/batches',{title:'Batch & Expiry',batches:await pharmacy.listBatches(req.user.id)});}catch(e){next(e);}}
async function suppliers(req,res,next){try{res.render('pharmacy/suppliers',{title:'Suppliers',suppliers:await pharmacy.listSuppliers(req.user.id)});}catch(e){next(e);}}
async function addSupplier(req,res,next){try{await pharmacy.createSupplier(req.body,req.user.id);req.flash('success','Supplier created.');res.redirect('/pharmacy/suppliers');}catch(e){if(e instanceof AppError){req.flash('errors',[{message:e.message}]);return res.redirect('/pharmacy/suppliers');}next(e);}}
async function addMedicine(req,res,next){try{await pharmacy.createMedicine(req.body,req.user.id);req.flash('success','Medicine created.');res.redirect('/pharmacy/inventory');}catch(e){if(e instanceof AppError){req.flash('errors',[{message:e.message}]);return res.redirect('/pharmacy/inventory');}next(e);}}
async function newSale(req,res,next){try{const[batches]=await pool.query('SELECT pb.id,pb.batch_number,pb.expiry_date,pb.mrp,pb.sale_rate,pb.quantity,pm.name,pm.sku FROM pharmacy_batches pb JOIN pharmacy_medicines pm ON pm.id=pb.medicine_id WHERE pm.branch_id=? AND pb.quantity>0 ORDER BY pm.name,pb.expiry_date LIMIT 1000',[req.user.branch_id]);const[patients]=await pool.query('SELECT id,health_id,name,mobile FROM patients WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 500');res.render('pharmacy/new-sale',{title:'Pharmacy POS',batches,patients});}catch(e){next(e);}}
async function createSale(req,res,next){try{const items=JSON.parse(req.body.itemsJson||'[]');const x=await pharmacy.createSale({...req.body,items},req.user.id);req.flash('success','Bill '+x.saleNumber+' created.');res.redirect('/pharmacy/sales/'+x.id);}catch(e){if(e instanceof AppError){req.flash('errors',[{message:e.message}]);return res.redirect('/pharmacy/sales/new');}next(e);}}
async function sales(req,res,next){try{res.render('pharmacy/sales',{title:'Pharmacy Sales',rows:await pharmacy.listSales(req.user.id)});}catch(e){next(e);}}
async function sale(req,res,next){try{const x=await pharmacy.getSale(req.params.id,req.user.id);if(!x)throw new AppError('Sale not found',404);res.render('pharmacy/sale-detail',{title:x.sale.sale_number,...x});}catch(e){next(e);}}
async function purchaseForm(req,res,next){try{res.render('pharmacy/purchase',{title:'Purchase / GRN',suppliers:await pharmacy.listSuppliers(req.user.id),medicines:await pharmacy.listMedicines(req.user.id)});}catch(e){next(e);}}
async function purchase(req,res,next){try{const items=JSON.parse(req.body.itemsJson||'[]');await pharmacy.postPurchase({...req.body,items},req.user.id);req.flash('success','Purchase posted and stock updated.');res.redirect('/pharmacy/inventory');}catch(e){if(e instanceof AppError){req.flash('errors',[{message:e.message}]);return res.redirect('/pharmacy/purchases/new');}next(e);}}
async function accounts(req,res,next){try{res.render('pharmacy/accounts',{title:'Pharmacy Accounts',rows:await pharmacy.accounts(req.user.id)});}catch(e){next(e);}}
async function expense(req,res,next){try{await pharmacy.addExpense(req.body,req.user.id);req.flash('success','Expense recorded.');res.redirect('/pharmacy/accounts');}catch(e){if(e instanceof AppError){req.flash('errors',[{message:e.message}]);return res.redirect('/pharmacy/accounts');}next(e);}}
module.exports={dashboard,inventory,batches,suppliers,addSupplier,addMedicine,newSale,createSale,sales,sale,purchaseForm,purchase,accounts,expense};